### ISSUE TITLE
Specificity of `progress[value]`

### ISSUE THREAD

**Issue by wooorm** [vandijkstef/cssttr#5]
https://github.com/vandijkstef/cssttr/blob/3bc76b460702d5e1dfa506f174893d6010d04d57/styles.css#L134

Why not use `progress` with the `[value]` part?

**Comment by vandijkstef** [comment]
I am using progress with [value]? Comment unclear

**Comment by wooorm** [comment]
Why is the `[value]` part needed?

**Comment by vandijkstef** [comment]
Based on https://css-tricks.com/html5-progress-element/ the [value] seemed required to style a progress bar with value. You are right, it works without the attribute selector.
